"use client";
import { useEffect, useState } from "react";
import { CheckoutVideoModal, CheckoutState } from "./CheckoutVideoModal";
type CartItem = { key?: string; id: string; name: string; price: number; quantity: number; color?: string; size?: string };
export default function CheckoutPage() {
 const [cartItems,setCartItems]=useState<CartItem[]>([]); const [modalState,setModalState]=useState<CheckoutState>(null); const [activeOrderId,setActiveOrderId]=useState(""); const [isSubmitting,setIsSubmitting]=useState(false); const [formData,setFormData]=useState({name:"",email:"",phone:"",address:"",city:""});
 useEffect(()=>{try{setCartItems(JSON.parse(localStorage.getItem("hadx-cart")||"[]"));}catch{setCartItems([])}},[]);
 const total=cartItems.reduce((s,i)=>s+i.price*i.quantity,0); const update=(k:keyof typeof formData,v:string)=>setFormData(f=>({...f,[k]:v}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const i=cartItems[0];if(!i?.id){setModalState("payment_failed");return}setIsSubmitting(true);try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId:i.id,quantity:i.quantity,color:i.color||"Black",size:i.size||"M",fullName:formData.name.trim(),email:formData.email.trim(),phone:formData.phone.trim(),address:`${formData.address.trim()}, ${formData.city.trim()}`,useStripe:false})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error);setActiveOrderId(d.orderReference||d.orderId);localStorage.removeItem("hadx-cart");setCartItems([]);setModalState("order_confirmed")}catch{setModalState("network_error")}finally{setIsSubmitting(false)}};
 const field=(k:keyof typeof formData,t:string,p:string)=><input required type={t} placeholder={p} value={formData[k]} onChange={e=>update(k,e.target.value)} className="w-full rounded-lg border border-neutral-800 bg-neutral-900 p-3 text-white outline-none focus:border-amber-500"/>;
 return <main className="min-h-screen bg-[#050505] px-6 py-28 text-white sm:px-12"><div className="mx-auto max-w-xl"><p className="mb-2 text-center font-mono text-[10px] tracking-[.3em] text-amber-500/80">[ SYSTEM :: COD CHECKOUT ]</p><h1 className="mb-10 text-center text-3xl font-extrabold text-amber-400">HADX LABS Secure Checkout</h1><section className="rounded-2xl border border-neutral-800 bg-neutral-950/80 p-6 shadow-2xl sm:p-8"><div className="mb-6 space-y-2 border-b border-neutral-800 pb-4">{cartItems.length?cartItems.map(i=><div key={i.key||i.id} className="flex justify-between font-mono text-xs"><span>{i.name} · {i.color||"Black"} / {i.size||"M"} × {i.quantity}</span><span className="text-amber-400">PKR {(i.price*i.quantity).toLocaleString()}</span></div>):<p className="text-sm text-neutral-500">Your loadout is empty.</p>}</div><form onSubmit={submit} className="space-y-4 font-mono text-xs">{field("name","text","Full name")}{field("email","email","Email address")}{field("phone","tel","+92 300 1234567")}<div className="grid grid-cols-2 gap-4">{field("address","text","Address")}{field("city","text","City")}</div><div className="flex items-center justify-between border-t border-neutral-800 pt-5"><span className="font-bold text-amber-400">PKR {total.toLocaleString()}</span><button type="submit" disabled={isSubmitting||!cartItems.length} className="rounded-xl bg-amber-500 px-6 py-3 font-bold tracking-wider text-black hover:bg-amber-400 disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting?"PROCESSING...":"EXECUTE ORDER"}</button></div><p className="text-[10px] uppercase tracking-widest text-neutral-600">Cash on delivery · Pakistan</p></form></section></div><CheckoutVideoModal state={modalState} orderId={activeOrderId} onClose={()=>setModalState(null)} onRetry={()=>setModalState(null)}/></main>;
}
